//tag::ref-doc[]
= processor-lcbo-pricelist-loader

The `lcbo-pricelist-loader` processor uses the LCBO REST API to query for whiskey products and published to an output stream. 

== Input

=== Headers

* N/A

=== Payload

* Ignored (trigger message used for starting process on a schedule)

== Output

=== Headers

* N/A

=== Payload

* `org.springframework.cloud.stream.app.lcbo.pricelist.loader.domain.LcboProduct` - whiskey products returned from the LCBO API.  Note that each trigger can result in many products being published in a single stream callback.

== Options

The **$$lcbo-pricelist-loader$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$lcbo.pricelist.loader.processor-url$$:: $$LCBO REST API URL with query string parameters (by default, searching for whiskies)$$ *($$String$$, default: `$$http://lcboapi.com/products?where_not=is_dead,is_discontinued&q=whisky$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar lcbo-pricelist-loader-processor-solace-0.0.1.BUILD-SNAPSHOT.jar --solace.java.host=192.168.65.3 --solace.java.msgVpn=default --solace.java.clientUsername=default --solace.java.clientPassword=default --spring.cloud.stream.bindings.input.destination=lcbo.pricelist.loader --spring.cloud.stream.bindings.input.group=group --spring.cloud.stream.solace.bindings.input.consumer.queueAdditionalSubscriptions=trigger/c2 --spring.cloud.stream.bindings.output.destination=lcbo/pricelist/loader --solace.java.apiProperties.generate_sender_id=true --solace.java.apiProperties.generate_sequence_numbers=true --solace.java.apiProperties.generate_send_timestamps=true
```

//end::ref-doc[]
